### ISSUE TITLE
error generating manifest for unresolved nodes with extract-vars-store-from-manifests.sh script 

### ISSUE THREAD

**Issue by phong2tran** [cloudfoundry/cf-deployment-transition#7]
We're in process of testing cf-deployment migration from cf-release and ran into this error when using extract-vars-store-from-manifests.sh script:

$ ./extract-vars-store-from-manifests.sh --ca-keys ../ca-keys.yml --cf-manifest ../manifests/cf-287.yml --diego-manifest ../manifests/cf-diego-1.35.0.yml
/tmp/tmp.4hzDL1MW6Y
2018/02/27 21:48:51 error generating manifest: unresolved nodes:
        (( merge ))     in /tmp/tmp.z3Nb90iMIU  jobs.[0].properties     (jobs.database_z1.properties)
2018/02/27 21:48:51 error generating manifest: unresolved nodes:
        (( merge ))     in /tmp/tmp.z3Nb90iMIU  jobs.[0].properties     (jobs.database_z1.properties)

If we added the nil option in the template (https://github.com/cloudfoundry/cf-deployment-transition/blob/master/templates/vars-pre-processing-template.yml#L179-L181) as below,

jobs:
- name: database_z1
  properties: (( merge || nil))

then the error went away.

What exact properties are expected for database_z1 job if required? If not, is adding "|| nil" option for ((merge)) expression expected?

**Comment by dsabeti** [comment]
Hi @phong2tran, our environments typically have a whole lot of properties in the `database_z1` instance group. Many of them are not actually set (they merely have empty values), but they definitely tend to have `loggregator.ca_cert` and `metron_agent.zone`. Does your `database_z1` instance group not have _any_ properties configured for them? 

I'm going to rope in @ematpl from the Diego team to see if he has any guidance about which properties must be configured. If it turns out that these properties aren't actually required, we can add a `|| nil` to that part of the template, I suppose.

**Comment by dsabeti** [comment]
Ok @phong2tran. After digging in, it looks like we mostly need to include that for operators who have deployed locket as part of their Diego deployment. We should probably remove the requirement that the properties be set.

**Comment by dsabeti** [comment]
Ok @phong2tran, try the latest commit: https://github.com/cloudfoundry/cf-deployment-transition/commit/a38b2b112d584f60d38f02e008eed1340db69676

**Comment by phong2tran** [comment]
Great, thanks for the fix @dsabeti!
